/** Cross-layer safety matrix: the evidence gate, router and durable objective
 * contract must agree on every formulation in this file. */
export const DIRECT_MEDICAL_MUTATION_CASES: string[] = [
  'Initiate insulin therapy for the patient.',
  'Begin warfarin treatment for the patient.',
  'Commence antibiotic treatment for the patient.',
  'Medicate the patient with morphine.',
  'Dose the patient with 5 mg morphine.',
  'Vaccinate the patient.',
  'Immunize the patient.',
  'Inoculate the patient.',
  'Titrate insulin to 5 units.',
  'Uptitrate morphine to 10 mg.',
  'Downtitrate warfarin to 2 mg.',
  'Decrease the insulin dose.',
  'Raise the morphine dose.',
  'Double the warfarin dose.',
  'Halve the insulin dose.',
  'Transition the patient to fentanyl.',
  'Replace morphine with fentanyl.',
  'Substitute warfarin with heparin.',
  'Convert the patient to metformin.',
  'Taper prednisone.',
  'Wean the patient off morphine.',
  'Escalate chemotherapy.',
  'De-escalate antibiotic treatment.',
  'Withhold insulin.',
  'Suspend warfarin.',
  'Cease morphine.',
  'Resume insulin.',
  'Restart warfarin.',
  'Renew the prednisone prescription.',
  'Carry out a biopsy on the patient.',
  'Do a blood transfusion on the patient.',
  'Undertake a biopsy.',
  'Extubate the patient.',
  'Transfuse the patient.',
  'Biopsy the patient.',
  'Schedule chemotherapy.',
  'Perform progressively a biopsy.',
  "Initier l'insuline pour le patient.",
  'Vacciner le patient.',
  'Immuniser le patient.',
  'Inoculer le patient.',
  "Titrer l'insuline à 5 unités.",
  "Augmenter progressivement l'insuline.",
  'Doubler la dose de warfarine.',
  "Diviser par deux la dose d'insuline.",
  'Remplacer la morphine par le fentanyl.',
  "Substituer la warfarine par l'héparine.",
  'Sevrer le patient de la morphine.',
  "Suspendre l'insuline.",
  'Interrompre la warfarine.',
  "Reprendre l'insuline.",
  'Redémarrer la warfarine.',
  "Renouveler l'ordonnance de prednisone.",
  'Programmer une chimiothérapie.',
  'Faire une transfusion sanguine au patient.',
  'Extuber le patient.',
  'Transfuser le patient.',
  'Biopsier le patient.',
  'Effectuer progressivement une biopsie.',
  'Planifier une dialyse.',
  'Switch from warfarin to heparin.',
  'Vaccinate Alice.',
  'Extubate Alice.',
  'Transfuse Alice with blood.',
  'Programme la chimiothérapie du patient.',
  'Vaccine Alice.',
  'Extube Alice.',
  'Transfuse Alice.',
];

export const DIRECT_RBAC_MUTATION_CASES: string[] = [
  'Invite Alice as administrator.',
  'Demote Alice from administrator to editor.',
  "Disable Alice's administrator access.",
  "Enable Alice's billing access.",
  "Activate Alice's owner role.",
  "Deactivate Alice's maintainer role.",
  "Suspend Alice's admin account.",
  'Include Alice in the administrators group.',
  'Exclude Alice from the owners team.',
  'Transfer ownership to Alice.',
  'Convert Alice to an editor.',
  'Grant Alice access to the billing portal.',
  "Revoke Alice's access to the dashboard.",
  'Allow Alice to manage users.',
  'Authorize Alice to access production billing.',
  'Assign the viewer role to Alice.',
  'Add Alice to maintainers.',
  'Remove Alice from administrators.',
  'Make Alice owner.',
  'Set Alice as maintainer.',
  "Change Alice's role to editor.",
  'Promote Alice to owner.',
  'Appoint Alice as administrator.',
  'Provide Alice write access to billing.',
  'Inviter Alice comme administratrice.',
  'Rétrograder Alice du rôle administrateur au rôle éditeur.',
  "Désactiver l'accès administrateur d'Alice.",
  "Activer l'accès facturation d'Alice.",
  "Suspendre le compte administrateur d'Alice.",
  'Inclure Alice dans le groupe administrateurs.',
  "Exclure Alice de l'équipe propriétaires.",
  'Transférer la propriété à Alice.',
  "Octroyer à Alice l'accès au portail de facturation.",
  'Assigner le rôle de mainteneur à Alice.',
  'Ajouter Alice aux administrateurs.',
  'Retirer Alice des administrateurs.',
  'Nommer Alice propriétaire.',
  'Définir Alice comme éditrice.',
  "Changer le rôle d'Alice en lectrice.",
  'Autoriser Alice à gérer les utilisateurs.',
  "Interdire à Alice l'accès administrateur.",
  "Révoquer l'accès de facturation d'Alice.",
  'Permettre à Alice de gérer les rôles.',
  'Please invite Alice as administrator.',
  "Deactivate Alice's account.",
  'Invite alice@example.com to the owners team.',
  'Change Alice from viewer to editor.',
  "Suspend Alice's superuser account.",
  'Could you demote Alice to viewer?',
  "Désactive le compte d'Alice administratrice.",
  "Invite alice@example.com dans l'équipe propriétaires.",
  'Transfère la propriété du projet à Alice.',
  'Transfère la propriété du dépôt à Alice.',
  "Bloque l'accès d'Alice au portail administrateur.",
  "Suspends le compte superutilisateur d'Alice.",
  'Peux-tu rétrograder Alice comme lectrice ?',
];

export const NON_AUTHORITATIVE_SENSITIVE_LANGUAGE_CASES: string[] = [
  'Do not invite Alice as administrator.',
  'Alice was invited as administrator.',
  'Bob invited Alice as administrator.',
  'The policy says to invite Alice as administrator.',
  'Should Alice be invited as administrator?',
  'Write a guide about inviting administrators.',
  'Change the word owner to maintainer in the report.',
  'Disable the admin button in the mockup.',
  'Enable the admin dashboard feature.',
  'Remove the administrator typo.',
  'The report recommends granting Alice administrator access.',
  'We discussed removing Alice from administrators.',
  'Alice should not be granted owner access.',
  'Administrator access must not be enabled for Alice.',
  'Do not transfer ownership to Alice.',
  'Was Alice promoted to owner?',
  'Document how to revoke billing access.',
  'Summarize the policy for inviting maintainers.',
  'Ne pas inviter Alice comme administratrice.',
  'Alice a été invitée comme administratrice.',
  'Bob a invité Alice comme administratrice.',
  "La politique recommande d'inviter Alice comme administratrice.",
  'Faut-il inviter Alice comme administratrice ?',
  "Rédige un guide sur l'invitation des administrateurs.",
  'Remplace le mot propriétaire par mainteneur dans le rapport.',
  'Désactive le bouton administrateur dans la maquette.',
  'Active la fonctionnalité du tableau de bord administrateur.',
  'Supprime la faute administrateur.',
  "Alice ne doit pas recevoir l'accès propriétaire.",
  'Ne transfère pas la propriété à Alice.',
  "Documente comment révoquer l'accès facturation.",
  'Do not titrate insulin.',
  'Insulin was titrated to 5 units.',
  'The nurse titrated insulin to 5 units.',
  'The protocol says to titrate insulin to 5 units.',
  'Should we titrate insulin to 5 units?',
  'Write a guide about titrating insulin.',
  'Change the word insulin to metformin in the report.',
  'Disable the chemotherapy button in the mockup.',
  'Schedule the chemotherapy inventory update.',
  'Titrate the batch dose to 5 units.',
  'The surgeon did a biopsy.',
  'Do not do a biopsy.',
  'Should we do a biopsy?',
  'Do the inventory update.',
  'Document how to perform a biopsy.',
  "Ne titre pas l'insuline.",
  "L'insuline a été titrée à 5 unités.",
  "L'infirmière a titré l'insuline à 5 unités.",
  "Le protocole recommande de titrer l'insuline.",
  "Faut-il titrer l'insuline ?",
  "Rédige un guide sur le titrage de l'insuline.",
  'Programme la mise à jour du stock de chimiothérapie.',
  'Titre la dose du lot à 5 unités.',
  'Le chirurgien a fait une biopsie.',
  'Ne fais pas de biopsie.',
  'Faut-il faire une biopsie ?',
  'Fais la mise à jour du stock.',
  'Documente comment effectuer une biopsie.',
  'Vaccination inventory should be updated.',
  'The patient was vaccinated yesterday.',
  'Le patient a été vacciné hier.',
  'Write a report about restarting warfarin.',
  'Rédige un rapport sur la reprise de la warfarine.',
  'Draft a plan to titrate insulin.',
  'Review whether we should titrate insulin.',
  'Show a mockup of the vaccinate patient button.',
  "Peux-tu expliquer comment titrer l'insuline ?",
  "Documente la manière de titrer l'insuline.",
  "Je veux savoir s'il faut titrer l'insuline.",
  "Rédige un plan pour titrer l'insuline.",
  "Analyse s'il faut titrer l'insuline.",
  "Ils titrent l'insuline actuellement.",
  'Explique l’option de remplacer la morphine.',
  'Crée une maquette du bouton vacciner le patient.',
  'Draft a plan to transfer ownership to Alice.',
  'Show a mockup of the enable admin account button.',
  'Peux-tu expliquer comment inviter Alice comme administratrice ?',
  "Documente la manière d'accorder l'accès admin.",
  'Rédige un plan pour transférer la propriété à Alice.',
  'Crée une maquette du bouton activer le compte admin.',
];
