#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,py_compile,sys
from datetime import datetime
from pathlib import Path
sys.path.insert(0,"/srv/rbw-agents-oss/scripts")
import robinswood_flow_core as c
import robinswood_flow_v2 as v
import robinswood_flow_contact_evidence_discovery as discovery
import contact_salutation
import robinswood_pme_hdf_reply_unsubscribe_loop as hdf_reply
import robinswood_commercial_post_remediation_control as commercial_postcheck
import robinswood_pme_hdf_recovery_cohort as hdf_recovery
import robinswood_flow_duplicate_relationship_audit as duplicate_audit
from outbound_content_guard import selftest as outbound_selftest,is_delivery_challenge,mentions_attachment
from sellsy_technical_duplicate_guard import is_technical_duplicate,item_references_duplicate,DUPLICATE_IDS
R=Path("/srv/rbw-agents-oss");O=c.OPS

def run_tests()->int:
 checks=[]
 def ck(name,value,detail=None):checks.append({"name":name,"ok":bool(value),"detail":detail})
 scripts=["outbound_content_guard.py","contact_salutation.py","robinswood_flow_v2.py","robinswood_flow_contact_enrichment.py","robinswood_flow_contact_evidence_discovery.py","robinswood_flow_public_qualification_merge.py","robinswood_flow_pre_audit.py","robinswood_flow_pre_audit_finalize.py","robinswood_flow_pre_audit_finalize_v4.py","robinswood_flow_email_sequencer_preaudit.py","robinswood_flow_sellsy_integrity.py","robinswood_flow_sellsy_sync.py","commercial_attribution_ledger.py","robinswood_pme_hdf_pre_send_gate.py","robinswood_pme_hdf_audited_mailer.py","robinswood_pme_hdf_reply_unsubscribe_loop.py","robinswood_pme_hdf_performance_optimizer.py","robinswood_pme_hdf_recovery_cohort.py","robinswood_commercial_post_remediation_control.py","robinswood_flow_duplicate_relationship_audit.py","source_lane_learning_governor.py","report_envelope_standardizer.py","system_of_record_reconciler.py","oss_autonomy_quality_guard_tests.py","robinswood_flow_structural_tests.py"]
 for name in scripts:
  try:py_compile.compile(str(R/"scripts"/name),doraise=True);ck("compile:"+name,True)
  except Exception as exc:ck("compile:"+name,False,str(exc))
 coresrc=(R/"scripts/robinswood_flow_core.py").read_text();ck("sellsy_cursor_pagination_fail_closed","page={p}" not in coresrc and "offset={quote" in coresrc and "sellsy_cursor_pagination_incomplete" in coresrc and "sellsy_cursor_pagination_short_read" in coresrc);ck("sellsy_full_scans_recovery_only","need_companies" in coresrc and "need_contacts" in coresrc and "if need_companies else []" in coresrc and "if need_contacts else []" in coresrc)
 syncsrc=(R/"scripts/robinswood_flow_sellsy_sync.py").read_text();ck("commercial_postcheck_integrated_single_owner","run_post_remediation_control" in syncsrc and "robinswood-commercial-post-remediation-control-last.json" in syncsrc and "newScheduleCreated" not in syncsrc)
 post=c.load(O/"robinswood-commercial-post-remediation-control-last.json",{});pc=post.get("counts") or {};ck("commercial_postcheck_live_green",post.get("ok") is True and post.get("status")=="passed_no_drift" and pc.get("sellsyMutations")==0 and pc.get("flowOpportunities")==0 and pc.get("unknownYousignMessages")==0 and pc.get("newHdfSendsWhileBlocked")==0,pc)
 recovery=c.load(O/"robinswood-pme-hdf-recovery-cohort-last.json",{});rc=recovery.get("counts") or {};rf=recovery.get("historicalMetricsFrozen") or {};sim=c.load(O/"robinswood-pme-hdf-recovery-simulated-plan.json",{});ck("hdf_recovery_cohort_non_consumable",recovery.get("ok") is True and rc.get("readyForOutbound")==0 and rc.get("approvedForSend")==0 and rf.get("sentCumulative")==48 and rf.get("laneHardBounces")==5 and sim.get("mailerConsumable") is False and sim.get("externalSendAllowed") is False and sim.get("approvedItemsCount")==0,{"counts":rc,"historical":rf,"simulated":sim.get("status")})
 diagnostic=c.load(O/"robinswood-commercial-lane-recovery-diagnostic-last.json",{});dl=diagnostic.get("lanes") or [];ck("four_lane_recovery_diagnostic",diagnostic.get("ok") is True and {x.get("laneId") for x in dl}=={"robinswood-flow","pme-hdf","abm-outreach","prescriber-network"} and all(x.get("decision") in {"hold","rework","retire","eligible_for_human_review"} and x.get("externalSendAllowed") is False for x in dl),{"status":diagnostic.get("status"),"lanes":[{"id":x.get("laneId"),"decision":x.get("decision")} for x in dl]})
 dup=c.load(O/"robinswood-flow-duplicate-relationship-audit-last.json",{});dc=dup.get("counts") or {};ck("duplicate_relationship_audit_read_only",dup.get("ok") is True and dc.get("objects")==25 and dc.get("duplicateCompanies")==13 and dc.get("duplicateContacts")==10 and dc.get("falsePositiveContacts")==2 and dc.get("endpointScansComplete")==dc.get("endpointScans")==6 and dc.get("hardDeletes")==0 and dc.get("archives")==0 and dc.get("crmMutations")==0,dc)
 policy=c.load(R/"config/system-of-record-policy.json",{});overrides=((policy.get("classification") or {}).get("explicitOverrides") or {});technical_ids={"source-lane-learning-governor","robinswood-pme-hdf-performance-optimizer","robinswood-pme-hdf-pre-send-gate","robinswood-flow-guard-tests","robinswood-commercial-post-remediation-control","robinswood-commercial-lane-diagnostic","robinswood-pme-hdf-recovery-cohort","robinswood-flow-duplicate-relationship-audit"};ck("technical_read_only_reports_need_no_business_payload",all((overrides.get(x) or {}).get("classification")=="none" for x in technical_ids),{x:(overrides.get(x) or {}).get("classification") for x in sorted(technical_ids)})
 ck("recovery_and_postcheck_selftests",hdf_recovery.selftest().get("ok") and commercial_postcheck.selftest().get("ok") and duplicate_audit.selftest().get("ok"),{"hdf":hdf_recovery.selftest(),"postcheck":commercial_postcheck.selftest(),"duplicates":duplicate_audit.selftest()})
 guard=outbound_selftest();ck("outbound_content_guard_matrix",guard.get("ok") and guard.get("attachmentMatrix"),guard)
 sal=contact_salutation.selftest();ck("salutation_neutral_and_explicit_only",sal.get("ok"),sal)
 challenge={"fromEmail":"artus@invitations.mailinblack.com","subject":"Un clic pour délivrer votre email !","bodyText":"Je suis protégé par Protect de Mailinblack"};challenge_class=hdf_reply.classify(challenge,challenge["bodyText"]);ck("mailinblack_delivery_challenge_fixture",is_delivery_challenge(challenge["fromEmail"],challenge["subject"],challenge["bodyText"]) and challenge_class=="delivery_challenge",challenge_class);replysrc=(R/"scripts/robinswood_pme_hdf_reply_unsubscribe_loop.py").read_text().lower();ck("mailinblack_no_suppression_no_auto_reply_no_delete",challenge_class=="delivery_challenge" and "automaticchallengeresponseallowed\":false" in replysrc and "gmail_send" not in replysrc and "requests.delete(" not in replysrc and "method=\"delete\"" not in replysrc)
 reg=c.load(c.REG,{});accounts=reg.get("accounts") or [];ck("generic_thirteen_accounts",len(accounts)==13,len(accounts));ck("only_yousign_approved_now",sum(x.get("approvedForSequence") is True for x in accounts)==1);ck("other_twelve_no_outbound",all(not x.get("externalFirstContactAllowed") for x in accounts if x.get("key")!=c.YKEY));ck("zero_opportunities_live",int(c.load(c.CRMSTATE,{}).get("opportunitiesCreated") or 0)==0)
 nowp=datetime.now(v.TZ);due=c.load(v.DUE_REPORT,{});tasks=due.get("tasks") or [];ck("thirteen_task_due_readbacks",len(tasks)==13 and all(v.dt(x.get("readbackDue")) and v.dt(x["readbackDue"])>nowp for x in tasks),{"count":len(tasks),"future":sum(bool(v.dt(x.get("readbackDue")) and v.dt(x["readbackDue"])>nowp) for x in tasks)});ck("due_manager_idempotency_shape",len({(x.get("taskId"),x.get("desiredDue")) for x in tasks})==13)
 fixtures={"positive":"Disponible pour un rendez-vous","referral":"Je vais vous mettre en relation avec notre directrice opérations","ooo_fr":"Réponse automatique : absent du bureau, de retour le 21 juillet 2026","bounce":"mailer-daemon permanent error status: 5.1.1","optout":"Merci de me désabonner","refusal":"Non merci, pas intéressé","ambiguous":"Merci pour votre message"};expected={"positive":"positive","referral":"referral","ooo_fr":"out_of_office","bounce":"hard_bounce","optout":"opt_out","refusal":"refusal","ambiguous":"ambiguous"};got={k:v.classify(t,t if k=="bounce" else "") for k,t in fixtures.items()};ck("reply_classification_fixtures",got==expected,got);ck("ooo_ambiguous_requires_human",not v.extract_return_date("Réponse automatique, absent quelques jours",datetime(2026,7,20,12,8,tzinfo=v.TZ)).get("reliable"))
 y=next(x for x in accounts if x.get("key")==c.YKEY);rec={"messageId":"fixture-positive-1","threadId":c.D0TID};p1=v.crm_action_for_signal(y,rec,"positive",dry_run=True);p2=v.crm_action_for_signal(y,rec,"positive",dry_run=True);ck("positive_one_task_one_opportunity_fixture",p1["taskCreates"]==1 and p1["opportunityCreates"]==1,p1);ck("positive_idempotency_markers",p1["taskMarker"]==p2["taskMarker"] and p1["opportunityMarker"]==p2["opportunityMarker"]);amb=v.crm_action_for_signal(y,{"messageId":"fixture-ambiguous","threadId":c.D0TID},"ambiguous",dry_run=True);ck("ambiguous_no_opportunity",amb["opportunityCreates"]==0,amb)
 ck("known_duplicate_ids_blocked",all(is_technical_duplicate({"id":x}) for x in DUPLICATE_IDS));ck("duplicate_marker_blocked",item_references_duplicate({"company":{"name":"[TECH DUPLICATE → 42] Example"}}));ck("canonical_ids_not_blocked",not item_references_duplicate({"sellsyCompanyId":57046867,"sellsyContactId":56542846}))
 eq=c.load(c.EMAILQ,{}).get("items") or [];liq=c.load(c.LIQ,{}).get("items") or [];ck("outbound_queues_yousign_only",all(x.get("accountKey")==c.YKEY for x in eq+liq));due_now=[x for x in eq+liq if x.get("status")=="scheduled_conditional" and v.is_due(x)];ck("no_due_dispatch_now",not due_now,[x.get("action_id") for x in due_now]);d5=next((x for x in eq if x.get("type")=="email_d5"),{});d14=next((x for x in eq if x.get("type")=="email_d14"),{});incident=c.load(O/"robinswood-flow-yousign-d5-attachment-incident.json",{});ck("yousign_d5_historical_incident_preserved",incident.get("status")=="contained_no_resend" and (incident.get("gmailEvidence") or {}).get("attachmentCount")==0 and (incident.get("gmailEvidence") or {}).get("bodyClaimedAttachment") is True and (incident.get("containment") or {}).get("resendAllowed") is False,incident);ck("yousign_d5_queue_not_rearmed",str(d5.get("status") or "").startswith("sent") and d5.get("preAuditAttachAllowed") is not True and not mentions_attachment(d5.get("body")),{"status":d5.get("status"),"attach":d5.get("preAuditAttachAllowed"),"bodyMentionsAttachment":mentions_attachment(d5.get("body"))});ck("yousign_d14_no_attachment",d14.get("attachmentsAllowed") is False and not mentions_attachment(d14.get("body")))
 seqsrc=(R/"scripts/robinswood_flow_email_sequencer_preaudit.py").read_text();ck("runtime_semantic_guard_before_send","attachment_meta(row,body)" in seqsrc and "outbound_content_reasons" in seqsrc and "if reasons:" in seqsrc and "sent_needs_manual_verification" in seqsrc);ck("gmail_post_send_readback_required","post=existing_exact" in seqsrc and "actualAttachmentCount" in seqsrc and "end_user_result_verified" in seqsrc)
 pf=c.load(O/"robinswood-flow-pre-audit-finalization-last.json",{});docs=pf.get("documents") or [];pfc=pf.get("counts") or {};ck("four_preaudits_passed",pfc.get("documents")==4 and pfc.get("passed")==4 and pfc.get("failed")==0,pfc);ck("all_preaudits_score_90_and_browser_green",len(docs)==4 and all(int(x.get("qualityScore") or 0)>=90 and (x.get("browserVisualControl") or {}).get("ok") is True and (x.get("control") or {}).get("pageCount")==1 for x in docs));ck("one_external_hash_bound_canary",pfc.get("externalEligible")==1 and pfc.get("visualCanaryPassed")==1 and any((x.get("visualCanary") or {}).get("required") and (x.get("visualCanary") or {}).get("valid") and (x.get("visualCanary") or {}).get("sourceHtmlHash")== (x.get("visualCanary") or {}).get("canaryHash") for x in docs),pfc);ck("preaudit_no_internal_jargon",all(not (x.get("control") or {}).get("forbiddenTerms") for x in docs))
 pack=c.load(O/"robinswood-flow-contact-enrichment-approval-pack.json",{});pi=pack.get("items") or [];ck("approval_pack_twelve_fail_closed",len(pi)==12 and all(x.get("approvedForSequence") is False and x.get("externalOutboundAllowed") is False and x.get("opportunityAllowed") is False for x in pi),{"items":len(pi),"counts":pack.get("counts")});ck("paid_wall_and_poc_preserved",pack.get("paidWallEur")==5000 and pack.get("minimumPocEur")==30000)
 crm=c.load(c.CRMSTATE,{});expected_contacts={"yousign-youtrust":56542846,"gitguardian":56542859,"filigran":56542860,"quarkslab":56542861};ck("canonical_four_contacts_exact",crm.get("contacts")==expected_contacts,crm.get("contacts"));integrity=c.load(O/"robinswood-flow-sellsy-integrity-last.json",{});second=integrity.get("secondReplay") or {};ck("sellsy_double_replay_idempotent",integrity.get("ok") is True and integrity.get("status")=="applied_read_back_double_replay_idempotent" and second.get("mutations")==0 and (integrity.get("stateHashes") or {}).get("secondReplayStable") is True,{"status":integrity.get("status"),"secondMutations":second.get("mutations")});ic=second.get("counts") or {};ck("sellsy_company_contact_roles_canonical",ic.get("contactsVerified")==4 and all(all(int((x.get("checks") or {}).get("companyContactRolesAfter",{}).get(f) or 0)==int(x.get("contactId")) for f in ("main_contact_id","invoicing_contact_id","dunning_contact_id")) for x in second.get("rows") or [] if x.get("contactId")));ck("sellsy_tasks_follow_taskupdateitem_single_relation",ic.get("tasksVerified")==13 and ic.get("taskContactRelations")==4 and all(set(tuple(y) for y in (x.get("checks") or {}).get("taskRelationsAfter",[]))==({("contact",x.get("contactId"))} if x.get("contactId") else {("company",x.get("companyId"))}) for x in second.get("rows") or []));ck("sellsy_no_delete_or_archive",ic.get("hardDeletes")==0 and ic.get("archives")==0)
 state_blob=json.dumps(crm);reg_blob=json.dumps(reg);queue_blob=json.dumps({"email":eq,"linkedin":liq});ck("duplicates_absent_from_state_registry_queues",all(str(x) not in state_blob+reg_blob+queue_blob for x in DUPLICATE_IDS))
 hdf=c.load(O/"robinswood-pme-hdf-performance-optimizer-last.json",{});hm=hdf.get("metrics") or {};ck("hdf_lane_denominator_48_sends_5_bounces",hm.get("sentCumulative")==48 and hm.get("laneHardBounces")==5 and abs(float(hm.get("hardBounceRate") or 0)-5/48)<0.0001,hm);ck("hdf_cross_campaign_bounces_excluded",int(hm.get("excludedCrossCampaignBounces") or 0)>=1,hm);ck("hdf_scaling_fail_closed",hm.get("scalingAllowed") is False and hm.get("recommendedMaxFirstSendsPerRun")==0 and hm.get("pauseRecommended") is True,hm);gate=c.load(O/"robinswood-pme-hdf-pre-send-gate-last.json",{});ck("hdf_gate_blocks_at_5_percent",gate.get("externalSendAllowed") is False and (gate.get("status") or "").startswith("blocked"),{"status":gate.get("status"),"blockingReasons":gate.get("blockingReasons")})
 attribution=c.load(O/"commercial-attribution-summary.json",{});ck("commercial_attribution_ledger_green",attribution.get("ok") is True and (attribution.get("counts") or {}).get("missingRequiredAttribution")==0,attribution.get("counts"));ck("commercial_horizons_7_30_90",set((attribution.get("horizons") or {}).keys())=={"7","30","90"});dash=c.load(O/"robinswood-commerce-dashboard.json",{});ck("dashboard_ledger_only",dash.get("sourceOfTruth")==str(O/"commercial-attribution-ledger.jsonl") and (dash.get("dataQuality") or {}).get("legacyCountersExcluded") is True)
 learning=c.load(O/"source-lane-learning-governor-last.json",{});ck("learning_uses_bounded_contract",learning.get("contractVersion")=="lane-learning-v2-commercial-ledger-bounded" and "no automatic outbound volume increase" in str((learning.get("method") or {}).get("safety")));outbound_decisions=[x for x in learning.get("decisions") or [] if x.get("laneId") in {"pme-hdf","robinswood-flow","abm-outreach","prescriber-network"}];ck("learning_never_auto_promotes_outbound",all(x.get("recommendedAction")!="promote_next_cycle" for x in outbound_decisions),outbound_decisions)
 st=discovery.selftest();ck("source_discovery_fail_closed_selftest",st.get("ok") and st.get("accountScoped") and st.get("twoFailureBackoff") and st.get("dueRetryBypassesDailyCache") and not st.get("outbound") and not st.get("crmMutation"),st);esc=c.load(O/"robinswood-flow-contact-evidence-escalation-queue.json",{});ck("all_retry_items_have_dates",all(x.get("nextRetryAt") for x in esc.get("items") or []),{"items":len(esc.get("items") or [])})
 sched=c.load(R/"config/temporal/ready-schedules.json",{});flow_sched=[x for x in sched.get("schedules") or [] if str(x.get("schedule_id") or "").startswith("sched.robinswood-flow-")];owner=next((x for x in flow_sched if x.get("schedule_id")=="sched.robinswood-flow-sellsy-sync"),{});ck("single_recurring_sellsy_mutation_owner",len(flow_sched)==8 and not any(x.get("schedule_id")=="sched.robinswood-flow-contact-enrichment" for x in flow_sched) and (owner.get("payload") or {}).get("legacy_id")=="robinswood-flow-sellsy-sync",{"count":len(flow_sched),"owner":owner.get("payload")})
 ok=all(x["ok"] for x in checks);payload={"generatedAt":c.now(),"contractVersion":"robinswood-flow-structural-tests-v6-commercial-recovery","capabilityId":"robinswood-flow-guard-tests","ok":ok,"status":"passed" if ok else "failed","counts":{"checks":len(checks),"passed":sum(x["ok"] for x in checks),"failed":sum(not x["ok"] for x in checks),"externalSends":0,"crmMutations":0,"opportunitiesCreated":0},"checks":checks};c.save(O/"robinswood-flow-guard-tests-last.json",payload);(O/"robinswood-flow-guard-tests-last.md").write_text(f"# Commerce structural tests v5\n\n- Passed: **{payload['counts']['passed']}/{len(checks)}**\n- External sends: **0**\n- CRM mutations from tests: **0**\n",encoding="utf-8");print(json.dumps({"ok":ok,"status":payload["status"],"counts":payload["counts"],"failed":[x["name"] for x in checks if not x["ok"]]},ensure_ascii=False));return 0 if ok else 1
if __name__=="__main__":raise SystemExit(run_tests())